
### 0. MyTEST
### GET http://localhost:8080/api/todos?category=就職活動
GET http://localhost:8080/api/todos?category=デザイン

### 1. 1件登録する
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "ｑｑｑｑｘｘｘ",
  "category": "プログラミング",
  "priority": 2,
  "dueDate": "2026-09-30"
}

### 2. 1件取得する
GET http://localhost:8080/api/todos/1

### 3. 1件更新する
PUT http://localhost:8080/api/todos/1
Content-Type: application/json

{
  "title": "APIで更新したやること",
  "detail": "更新後のメモ",
  "category": "プログラミング",
  "priority": 2,
  "dueDate": "2026-09-30",
  "completed": false
}

### 4. 1件削除する
DELETE http://localhost:8080/api/todos/34

### 5. 祝日を直接取ってくる
GET https://holidays-jp.github.io/api/v1/date.json

### 6. 自分のアプリの祝日API
GET http://localhost:8080/api/holidays


### 7. 自分のアプリの祝日API-期間で日付首都k
GET http://localhost:8080/api/todos?from=2026-09-01&to=2026-09-30
